apiVersion: v1
data:
  superset_config.py: IyBzdXBlcnNldF9jb25maWcucHkKaW1wb3J0IG9zCgoKClNFQ1JFVF9LRVkgPSAiZGpBSmFrejYxVEM0VWVZb09EQUtGaVFsZ2IwalM4NVJvMkNGejZBWTN3cz0iICAjIMO2cm5layBnw7zDp2zDvCBrZXkKCiMgQ2FjaGUgeWFwxLFsYW5kxLFybWFzxLEKQ0FDSEVfQ09ORklHID0gewogICAgJ0NBQ0hFX1RZUEUnOiAnUmVkaXNDYWNoZScsCiAgICAnQ0FDSEVfREVGQVVMVF9USU1FT1VUJzogMzAwLAogICAgJ0NBQ0hFX0tFWV9QUkVGSVgnOiAnc3VwZXJzZXRfJywKICAgICdDQUNIRV9SRURJU19VUkwnOiAncmVkaXM6Ly9zdXBlcnNldC1yZWRpcy1oZWFkbGVzczo2Mzc5LzEnCn0KCiMgR8O8dmVubGkgb2xtYXlhbiBnZWxpxZ90aXJtZSBvcnRhbcSxIGnDp2luCkVOQUJMRV9QUk9YWV9GSVggPSBUcnVlClNFU1NJT05fQ09PS0lFX1NBTUVTSVRFID0gIkxheCIKU1VQRVJTRVRfV0VCU0VSVkVSX1RJTUVPVVQgPSA2MAoKIyBWYXJzYXnEsWxhbiBvdHVydW0gbGltaXRpClRBTElTTUFOX0VOQUJMRUQgPSBGYWxzZQpXVEZfQ1NSRl9FTkFCTEVEID0gRmFsc2UKCg==
kind: Secret
metadata:
  name: superset-config
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: superset
    meta.helm.sh/release-namespace: default
